name: DNN-based_source_separation_wsj0-mix

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.8
  - numpy=1.19
  - scipy=1.6.1
  - matplotlib==3.3.2
  - pytorch=1.8.0
  - pyaudio=0.2
  - mir_eval==0.6