name: DNN-based_source_separation_tutorials

channels:
  - conda-forge
  - pytorch

dependencies:
  - python>=3.6,<=3.9
  - numpy>=1.19
  - matplotlib>=3.3.2
  - pytorch>=1.8.0
  - torchaudio>=0.8.0
  - mir_eval==0.6
  - pyaudio>=0.2.11