name: DNN-based_source_separation_tutorials

channels:
  - conda-forge
  - pytorch

dependencies:
  - python>=3.7,<3.9
  - numpy>=1.19
  - matplotlib>=3.3.2
  - ipython~=5.5.0
  - pytorch>=1.8.0
  - torchaudio>=0.8.0
  - mir_eval==0.6