in_channels: 2
bands: [low, middle]
low:
  sections: 192
  num_features: 32
  growth_rate: [16, 18, 18, 20, 18, 16, 16]
  kernel_size: 3
  scale: 2
  num_d2blocks: [2, 2, 2, 2, 2, 2, 2]
  dilated: [True, True, True, True, True, True, True]
  norm: [True, True, True, True, True, True, True]
  nonlinear: [relu, relu, relu, relu, relu, relu, relu]
  depth: [4, 5, 5, 4, 4, 4, 4]
middle:
  sections: 1408
  num_features: 8
  growth_rate: [2, 2, 2, 2, 2, 2, 2]
  kernel_size: 3
  scale: 2
  num_d2blocks: [1, 1, 1, 1, 1, 1, 1]
  dilated: [True, True, True, True, True, True, True]
  norm: [True, True, True, True, True, True, True]
  nonlinear: [relu, relu, relu, relu, relu, relu, relu]
  depth: [1, 1, 1, 1, 1, 1, 1]
full:
  num_features: 30
  growth_rate: [10, 10, 12, 14, 16, 14, 12, 8, 8]
  kernel_size: 3
  scale: 2
  num_d2blocks: [3, 3, 3, 5, 7, 5, 3, 2, 2]
  dilated: [True, True, True, True, True, True, True, True, True]
  norm: [True, True, True, True, True, True, True, True, True]
  nonlinear: [relu, relu, relu, relu, relu, relu, relu, relu, relu]
  depth: [2, 2, 2, 2, 2, 2, 2, 2, 2]
final:
  growth_rate: 14
  kernel_size: 3
  dilated: True
  depth: 3
  norm: True
  nonlinear: relu
comment:
  "This configuration file is based on https://github.com/sony/ai-research-code/blob/master/d3net/music-source-separation/configs/bass.yaml."