name: DNN-based_source_separation_py39

channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - python>=3.9
  - numpy>=1.19
  - matplotlib>=3.1.3
  - pytorch>=1.9.0
  - torchaudio>=0.9.0
  - pip
  - pip:
    - musdb==0.4.0
    - museval==0.4.0