control:
  backbone: dense
  channels: [4, 16, 32, 64] # 4 because of [drums, bass, other, vocals]
  nonlinear: 'relu'
  dropout: True
  norm: True
unet:
  channels: [2, 8, 16, 32] # 2 because of stereo
  kernel_size: 3
  stride: 2
  nonlinear_enc: ['leaky-relu', 'leaky-relu', 'leaky-relu', 'leaky-relu']
  nonlinear_dec: ['leaky-relu', 'leaky-relu', 'leaky-relu', 'sigmoid']
    